[
    {
        "message": "Module exception: something went wrong in module: division by zero (ZeroDivisionError).",
        "severity": 0,
        "origin": "exception_scheme_tester.py:4 --> project.py/faulty_module_function:393",
        "origin_timestamp": "2024-09-19-23-36-44",
        "registration_timestamp": "2024-09-19-23-36-44",
        "reported": true,
        "reported_timestamp": "2024-09-20-10-52-07",
        "checked": true,
        "checked_timestamp": "2024-09-20-10-52-07"
    }
]
