[
    {
        "exception_type": "Test exception 2",
        "severity": 2,
        "origin": "error_registration_tester.py:main_scope/foo:6",
        "origin_timestamp": "2024-09-18-15-32-33",
        "registration_timestamp": "2024-09-18-15-32-33",
        "reported": true,
        "reported_timestamp": "2024-09-18-15-36-30",
        "checked": false,
        "checked_timestamp": null
    },
    {
        "exception_type": "Test exception 3",
        "severity": 2,
        "origin": "error_registration_tester.py:main_scope/foo:6",
        "origin_timestamp": "2024-09-18-15-32-42",
        "registration_timestamp": "2024-09-18-15-32-42",
        "reported": true,
        "reported_timestamp": "2024-09-18-15-36-30",
        "checked": false,
        "checked_timestamp": null
    },
    {
        "exception_type": "Test exception 4",
        "severity": 2,
        "origin": "error_registration_tester.py:main_scope/foo:6",
        "origin_timestamp": "2024-09-18-15-32-46",
        "registration_timestamp": "2024-09-18-15-32-46",
        "reported": true,
        "reported_timestamp": "2024-09-18-15-36-30",
        "checked": false,
        "checked_timestamp": null
    },
    {
        "exception_type": "ProjectBaseException",
        "severity": 0,
        "origin": null,
        "origin_timestamp": "2024-09-19-13-35-35",
        "registration_timestamp": "2024-09-19-13-35-35",
        "reported": true,
        "reported_timestamp": "2024-09-19-13-36-42",
        "checked": false,
        "checked_timestamp": null
    },
    {
        "exception_type": "GitOperationError",
        "severity": 2,
        "origin": "data_uploader.py/main_scope/sync_dir_with_repo:288",
        "origin_timestamp": "2024-09-19-14-12-31",
        "registration_timestamp": "2024-09-19-14-12-31",
        "reported": true,
        "reported_timestamp": "2024-09-19-14-12-41",
        "checked": false,
        "checked_timestamp": null
    }
]