{"timestamp": "2024-12-24-07-15-04", "message": "Module error while trying to update local heating control config: failed to download sheet '<googleapiclient.discovery.Resource object at 0xf48a3530>' from spreadsheet 'Kaz\u00e1nf\u0171t\u00e9s heating control config': <HttpError 503 when requesting https://sheets.googleapis.com/v4/spreadsheets/1sXoPC301Wurbm7yW5A956dlFEJcwM-fIb090fKOxROw/values/Sheet1%21A1%3AZ10000?alt=json returned \"The service is currently unavailable.\". Details: \"The service is currently unavailable.\"> (HttpError).", "severity": 2, "origin": "schedule_and_config_updater.py/update_local_heating_control_config:86 --> project.py/download_google_sheet_to_2D_array:1565", "origin_timestamp": "2024-12-24-07-10-29", "registration_timestamp": "2024-12-24-07-10-29"}
