{"timestamp": "2024-09-12-20-34-33", "exception_type": "Test exception", "severity": 3, "origin": "error_registration_tester.py:main_scope/foo:6", "origin_timestamp": "2024-09-12-20-34-04", "registration_timestamp": "2024-09-12-20-34-04", "reported": false, "reported_timestamp": null, "checked": false, "checked_timestamp": null}
