{"timestamp": "2025-01-28-03-15-04", "message": "Module error while trying to scrape and log external temperature: failed to interact with node 'system' via get: HTTPSConnectionPool(host='kazanfutes-71b78-default-rtdb.europe-west1.firebasedatabase.app', port=443): Max retries exceeded with url: /system/.json (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:992)'))) (SSLError).", "severity": 2, "origin": "external_temp_scraper_and_logger.py:10 --> project.py/__init__:244 --> project.py/read:270 --> project.py/interact:264", "origin_timestamp": "2025-01-28-03-10-08", "registration_timestamp": "2025-01-28-03-10-08"}
